[package]
name = "polyengine"
version = "0.1.0"
authors = [
    # Extend this list when submiting PR
    "Michał Majczak <michal.majczak92@gmail.com>"
    ]
edition = "2018"
crate-type = ["dylib"]

[features]
networking = []

[dependencies]
polyengine-core = {path = "../core", features=[]}